### ISSUE TITLE
Configuração do  Módulo

### ISSUE THREAD

**Issue by felipejet** [rafaelpatro/Quack_TntBrasil#1]
Rafael tudo bom?

Achei interessante você ter criado esse módulo, vai me ajudar bastante rs

Poderia me ajudar em uma dúvida? após a instalação do módulo onde ele deveria aparecer? pois não encontrei em lugar nenhum no painel administrativo do magento.

Obrigado.

**Comment by rafaelpatro** [comment]
Após instalado deve aparecer uma opção adicional de exportação na tela de pedidos. E tb um botão para importar, na mesma tela.
Obrigado. Assim q der eu coloco mais informações.

**Comment by dcbasso** [comment]
Aproveitando a Issue, gostaria de saber em que pé esta o módulo.
Totalmente funcional? Se eu precisar de suporte e etc, você atende fazendo a instalação/configuração e ajuste do que for necessário? Quando ou como você cobra para atender, caso o faça.

Att

**Comment by rafaelpatro** [comment]
Olá @dcbasso! Sim, o módulo está funcional.
Acho que o rastreamento está com um pequeno defeito, que devo corrigir em breve.
Se precisar de suporte para a instalação ou customização, entre em contato: rafaelpatro@gmail.com.
